FROM python:3.6.1-alpine AS base
WORKDIR /app
COPY app.py /app.py
RUN pip install --upgrade pip
RUN pip install -U pip setuptools wheel
RUN pip install markupsafe
RUN pip install flask

FROM base AS requirements
COPY ./requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt
COPY . .
CMD ["python","app.py"]