apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-green
spec:
  selector:
    matchLabels:
      app: green
  template:
    metadata:
      labels:
        app: green
    spec:
      containers:
      - name: green-app
        image: kubedevio/nginx-color:green