apiVersion: apps/v1
kind: Deployment
metadata:
  name: meu-primeiro-deployment
spec:
  replicas: 11
  selector:
    matchLabels:
      app: exemplo
  template:
    metadata:
      labels:
        app: exemplo
    spec:
      containers:
      - name: meu-container-do-primeiro-deployment
        image: kubedevio/nginx-color:green