FROM wordpress:php8.1-fpm-alpine AS base

RUN echo "teste"

CMD ["php-fpm"]


FROM php:8.1-fpm-alpine3.16

RUN apk update && apk upgrade
RUN apk add bash
RUN apk add php8-gd php8-zlib php8-curl
RUN mkdir /var/run/php
RUN apk add php8-common php8-session php8-iconv php8-json php8-gd php8-curl php8-xml php8-mysqlnd php8-mysqli php8-imap php8-cgi fcgi php8-pdo php8-pdo_mysql php8-soap php8-posix php8-gettext php8-ldap php8-ctype php8-dom php8-simplexml
#RUN docker-php-ext-install nd_mysqli pdo pdo_mysql && docker-php-ext-enable nd_mysqli
RUN docker-php-ext-install pdo pdo_mysql && docker-php-ext-enable pdo_mysql
RUN mkdir -p /var/www/html
RUN mkdir -p /usr/src/wordpress/
RUN apk add less vim git mysql-client libssh2 curl libpng freetype libjpeg-turbo libgcc libxml2 libstdc++ icu-libs libltdl libmcrypt

COPY ./php.ini /etc/php8/php.ini
COPY --from=base /usr/src/wordpress/ /usr/src/wordpress/
WORKDIR /var/www/html
COPY --from=base /var/www/html /var/www/html
EXPOSE 9000
CMD ["php-fpm"]