apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: meu-replica-set-com-replicas-especificadas
spec:
  replicas: 7
  selector:
    matchLabels:
      app: exemplo
  template:
    metadata:
      labels:
        app: exemplo
    spec:
      containers:
      - name: meucontainerreplicado
        image: kubedevio/nginx-color:blue